# Generated by Django 5.0.7 on 2024-07-11 04:06

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('post_author', models.CharField(max_length=50)),
                ('post_content', models.TextField()),
                ('post_title', models.CharField(max_length=30)),
                ('post_resume', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
