# Generated by Django 5.0.7 on 2024-07-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_id_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment_post_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
