# Generated by Django 5.0.7 on 2024-07-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_author_comment_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=100),
        ),
    ]
